.\"                              hey, Emacs:   -*- nroff -*-
.\" cprec is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; see the file COPYING.  If not, write to
.\" the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.\" .TH CPREC 1 "November 22, 2007"
.\" .TH CPREC 1 "January 17, 2010"
.\" .TH CPREC 1 "September 1, 2014"
.TH CPREC 1 "November 9, 2015"
.\" Please update the above date whenever this man page is modified.
.\"
.\" Some nroff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins (default)
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
cprec \- A recursive directory hierarchy copier (like `cp -R')
with additional features to backup DVD video.
.SH SYNOPSIS
.B cprec
.RI [ options ]
[\-\fBn\fP \fIdvd_node\fP \-\fBd\fP <\fI0\(en\100\fP>]
<\fIsource\fP \fI...\fP> <\fItarget\fP>
.SH DESCRIPTION
\fBcprec\fP copies directory hierarchies, and optionally video DVD data
using
.nh
\fIlibdvdread\fP
.hy
(including decryption if
.nh
\fIlibdvdcss\fP
.hy
is available).
.PP
Copying is always recursive for directory source arguments, like `cp -R'.
Optionally, metadata (times, ownership and mode) may be
preserved in the copy, and operation may be forced to proceed,
i.e. overwriting existing targets and continuing
as well as possible after errors.
.PP
Functionality of the \fIcp\fP command is reimplemented in \fIcprec\fP
so that a backup of a video DVD may be made
as a copy of the entire directory hierarchy on the DVD. If desired,
the output directory can then be the source for a new DVD filesystem
(made with a program such as
.BR mkisofs (1)
or
.BR genisoimage (1)).
.PP
Additional material can be added to the output directory
along with the DVD file hierarchy in one command.
For example, scans of
cover images or included booklets, relevant images and web pages, and
video format conversions might be conveniently stored \fIwithin\fP
the backup.
.PP
There is one important difference from the behavior of \fIcp\fP
that a user should be aware of. When making a DVD backup, if
the output target is an existing directory, the DVD mount point
will not be copied under the target, only the source contents.
See the examples section.
.PP
The \fIcprec\fP program is intended for backups.
It behooves the user to be aware of pertinent laws to which
he or she is subjected, and to act appropriately.
.SH OPTIONS
\fBcprec\fP accepts the following options:
.\" dry-run has been disabled in the program (unmaintained).
.\" .TP
.\" .B  \-\-dry-run
.\" Take no real actions.
.TP
.BR  \-q , " \-\-quiet" , " \-\-silent"
Inhibit usual output.
.TP
.BR  \-v , " \-\-verbose"
Print more information.
.TP
.BR  \-d , " \-\-dvdbackup" " \fIN\fP"
Perform video DVD backup if
.nh
\fIlibdvdread\fP
.hy
is available and a suitable version.
If \fBN\fP is \fI0\fP then a full dvd backup is done.
If greater than \fI0\fP
but less than \fI100\fP then a single title set is selected.
If \fI100\fP then
.nh
`\fBVIDEO_TS.VOB\fP'
.hy
is selected.
The \-\fBn\fP <\fInode\fP> argument must be given with \-\fBd\fP
if the default \(em probably
.nh
`\fB/dev/dvd\fP'
.hy
\(em is not the correct
device node.
At least one
.nh
<\fIsource\fP>
.hy
argument must be the mount point of
the mounted DVD (such that the
.nh
`\fBVIDEO_TS\fP'
.hy
directory is a child of that argument).
.TP
.BR  \-n , " \-\-node" " <\fIdevice_node\fP>"
The raw device node associated with the DVD reader.
For example, on \fIGNU/Linux\fP it might be \fB/dev/sr0\fP,
on \fINetBSD\fP on an i386 it might be \fB/dev/rcd0d\fP.
The default is
.nh
`\fB/dev/dvd\fP'
.hy
(unless changed before configuration; try
CFLAGS="$CFLAGS -DDEFAULT_DVD_NODE=\\\\\\"/dev/<your node here>\\\\\\"").
As of \fIcprec\fP version 0.1.3 the mount point for a mounted
device may be given and \fIcprec\fP will try to find the device
node.
.TP
.BR \-s , " \-\-simple\-copy"
Simply copy files and do nothing special for video DVD entries;
no use of
.nh
\fIlibdvdread\fP.
.hy
This is the default without \-\fBd\fP.
.TP
.BR \-E , " \-\-ignore-existing"
Do not fail if target file exists, and do not overwrite it.
.TP
.BR \-S , " \-\-ignore-symlinks"
Do not make equivalent symbolic links; copy link target to new file.
.TP
.BR \-H , " \-\-ignore-hardlinks"
Do not make equivalent hard links; copy data to new file.
.TP
.BR \-D , " \-\-ignore-specials"
Do not make equivalent device nodes or pipes. Unix domain sockets
are always ignored. Various systems have other special types
which are always ignored with a message on standard error.
.TP
.BR \-N , " \-\-ignore-nonreadable"
Do not fail if a source directory is not readable.
.TP
.BR \-p , " \-\-preserve"
Attempt to set time and mode on output from input.
Failure is never fatal.
.TP
.BR \-f , " \-\-force"
Forceful operation. Overwrite existing output files, and try
to continue after errors which by default cause an exit with failure.
.TP
.BR  \-L , " --libdvdr" " \fINAME\fP"
Use shared library \fINAME\fP as the DVD reader.
Only available if configured for runtime loading of the library
(which is the default).
The argument must lead to
.nh
\fIlibdvdread\fP,
.hy
(regardless of name)
and it might be necessary to set the
.nh
\fCLD_LIBRARY_PATH\fP
.hy
environment variable suitably.
.TP
.BR  \-b , " \-\-block-read-count" " <\fIpositive integer\fP>"
Specify the the number of 2048 byte blocks to
request with each read.
.TP
.BR  \-r , " \-\-retry-block-count" " <\fIpositive integer\fP>"
On IO error, \fIcprec\fP will try again, but the block
read count (-b) is divided into several reads of this size.
If this smaller read fails, then \fIcprec\fP uses zeroes
(0) for the output blocks and continues (which is probably
acceptable for DVD video backup because the affect on
playback might be acceptable to a human viewer; so far
all playback machines have handled zeroed data well).
If the possibility of zeroed blocks is unacceptable then
give `0' for this option and \fIcprec\fP will fail rather
than retry. The default is non-zero (48 presently).
.TP
.BR \-h , " \-\-help"
Show summary of options and exit.
.TP
.BR \-V , " \-\-version"
Show version information and exit.
.\" .nh
.SH ENVIRONMENT
See the source code.
.SH EXAMPLES
.PP
If the drive device node is \fI/dev/dvd\fP and is mounted on
\fI/mnt\fP and output should be rooted in \fIbackup\fP,
and \fIbackup\fP does not exist yet or it is an existing
directory, and metadata should be preserved, and you would like
verbosity:
.IP
.nf
\fC% cprec -p -v -d 0 -n /dev/dvd /mnt backup\fP
.fi
.PP
If \fIbackup\fP did not exist it would have been
created as a directory, and on completion it
would have contained a backup
copy of everything found under \fI/mnt\fP including
extra materials that may have been present. If
\fIbackup\fP did exist
but was not a directory, \fIcprec\fP would have failed
with an error message. If \fIbackup\fP was an existing
directory, the result would have been \fBthe same\fP
as if it hadn't existed; that is, \fIcprec\fP would not
have created \fIbackup/mnt\fP as \fIcp\fP would have,
but instead would have  started at the contents of
\fI/mnt\fP. This behavior should allow \fIbackup\fP
to be given as the argument to a command such as mkisofs(1).
.PP
As of version 0.1.3, the example above may be shortened,
such as:
.IP
.nf
\fC% cprec -p -v -d 0 -n /mnt backup\fP
.fi
.PP
Note that the argument to -n is now \fI/mnt\fP and its
former argument \fI/dev/dvd\fP is absent, leaving only
one target argument after the options. This form of
command is recognized only if a -dN option is given.
In this command form, \fIcprec\fP will try to
determine if \fI/mnt\fP is a directory. If it is,
it will be used as the source argument, resolving
symbolic links and relative path.
.PP
The simple shortened command above also shows new
behavior introduced with \fIcprec\fP version
0.1.3: the -n (--node) option may be given an
argument that is a mount point for a mounted
device, and \fIcprec\fP will try to find the
associated device node.
.PP
When not making a DVD backup (using \fI-d\fP)
\fIcprec\fP will behave
like \fIcp\fP, so whether or not \fIbackup\fP exists
the following commands are equivalent:
.IP
.nf
\fC% cprec -pv /mnt backup\fP
.fi
.IP
.nf
\fC% cp -R -p -v /mnt backup\fP
.fi
.PP
If additional materials should be included with the
backup, give their names as arguments \fBbefore\fP
the DVD mount point:
.IP
.nf
\fC% cprec -pvd 0 -n /dev/dvd ~/stuff/pages cover.png /mnt backup\fP
.fi
.PP
It is important that the mount point be after other sources
when \fI-p\fP is given because after \fIcprec\fP copies
the DVD contents it will apply metadata to the target,
and the mount point will probably not include write
permission for a mounted DVD; subsequent attempts to
create files under the target fail. This is due to
the implementation which is effectively separate
operations for DVD and non-DVD sources. The author
does not presently feel this problem is worthy of repair;
simply make the mount point the last argument before
the target.
.PP
Finally, it is possible to backup a selected title set. This is
a special case in that the \fIVIDEO_TS\fP directory is not
created. The video files will be placed under the target
directly. Additional materials are optional and will be
copied recursively. If the desired title set is number 2:
.IP
.nf
\fC% cprec -pvd 2 -n /dev/dvd additional-stuff /mnt backup\fP
.fi
.PP
Note that the menu file for the title set is copied too.
.SH COPYRIGHT
Copyright \(co 2014 Ed Hynan. Source code license is the GNU
General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY.
.SH AUTHOR
Ed Hynan <edhynan@gmail.com>.
.SH "SEE ALSO"
.BR cp (1), 
.BR mkisofs (1),
.BR genisoimage (1),
.BR growisofs (1),
.BR cdrecord (1).
